# Generated by Django 6.0.2 on 2026-04-23 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('salary_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_number', models.CharField(max_length=20)),
                ('pay_period', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_days', models.IntegerField(blank=True, null=True)),
                ('leave_days', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_rec_employe_a6741c_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_rec_pay_per_890f92_idx',
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee_id'], name='payroll_employe_21225c_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['account_number'], name='payroll_account_7fbdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['pay_period'], name='payroll_pay_per_ad0151_idx'),
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='bank_account',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
