package models

import "time"

// FraudAlert represents a suspected fraud case generated by the
// detection engine and reviewed by auditors.
type FraudAlert struct {
	ID           string
	AlertType    string // ghost_worker, duplicate_bank_account, identity_reuse
	Severity     string // low / medium / high
	Status       string // open / in_review / closed
	Description  string // summary of the issue
	Explanation  string // plain-language reason for alert
	CreatedAt    time.Time
}
