# Generated by Django 5.1.9 on 2026-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_failed_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('fraud_analyst', 'Fraud Analyst'), ('compliance_officer', 'Compliance Officer'), ('auditor', 'External Auditor'), ('manager', 'Customer Success Manager')], default='', max_length=50),
        ),
    ]
